mvtec:
  datadir: "/DATA/Users/amahmood/GDrive/MVTec_AD/"
  datadir_gdrive: "/content/drive/MyDrive/ML_Datasets/MvTec_AD/"
  shape: 128, 128, 3   # Shape for training after crop
  downsample: 256, 256, 3  # Shape after downsampling (before crop)
  batch_size: 32

